# Generated by Django 5.1.7 on 2025-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('desired_region', models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기/인천'), ('busan', '부산/울산/경남'), ('daegu', '대구/경북'), ('gwangju', '광주/전남/전북'), ('daejeon', '대전/충남/충북'), ('gangwon', '강원'), ('jeju', '제주')], max_length=20)),
                ('career_break', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
