# Generated by Django 5.1.7 on 2025-07-09 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('planning', '기획/전략'), ('development', 'IT/개발/데이터'), ('manufacturing', '생산/제조'), ('contents', '콘텐츠/미디어'), ('marketing', '마케팅/홍보/MD'), ('customer_service', '고객상담/cs'), ('construction', '건축/시설관리'), ('finance', '금융/보험'), ('accounting', '회계/세무/재무'), ('logistics', '물류/운송'), ('healthcare', '의료/간호'), ('public', '공공/복지'), ('design', '디자인'), ('operation', '운영/서비스업'), ('education', '교육/강의'), ('hr', '인사/사무/총무')], max_length=20)),
                ('region', models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기/인천'), ('busan', '부산/울산/경남'), ('daegu', '대구/경북'), ('gwangju', '광주/전남/전북'), ('daejeon', '대전/충남/충북'), ('gangwon', '강원'), ('jeju', '제주')], max_length=20)),
                ('remote_available', models.BooleanField(default=False)),
                ('career', models.CharField(choices=[('new', '신입'), ('none', '없음'), ('exp', '경력')], max_length=10)),
                ('career_years', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(choices=[('high_school', '고등학교 졸업'), ('associate_degree', '전문대학 졸업'), ('bachelor_degree', '학사 학위'), ('master_degree', '석사 학위'), ('doctorate', '박사 학위')], max_length=20)),
                ('company_size', models.CharField(choices=[('small', '소기업'), ('medium', '중기업'), ('large', '대기업'), ('startup', '스타트업'), ('public', '공공기관')], max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='company_logo')),
                ('link', models.URLField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
            ],
            options={
                'unique_together': {('user', 'job_post')},
            },
        ),
    ]
