# Generated by Django 5.1.7 on 2025-07-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='career',
            field=models.CharField(choices=[('total', '전체'), ('new', '신입'), ('none', '없음'), ('exp', '경력')], max_length=10),
        ),
    ]
