# Generated by Django 5.1.7 on 2025-07-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='company_logo'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
