# Generated by Django 5.1.7 on 2025-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_company_logo_jobpost_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
