# Generated by Django 5.2.4 on 2025-07-11 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CounselComment',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='CounselPost',
        ),
    ]
