# Generated by Django 5.2.4 on 2025-07-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsel', '0002_rename_comment_counselcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='counsel.counselpost'),
        ),
    ]
