# Generated by Django 5.2.4 on 2025-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
