# Generated by Django 5.2.4 on 2025-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='desired_job',
            field=models.CharField(choices=[('planning', '기획/전략'), ('development', 'IT/개발/데이터'), ('manufacturing', '생산/제조'), ('contents', '콘텐츠/미디어'), ('marketing', '마케팅/홍보/MD'), ('customer_service', '고객상담/CS'), ('construction', '건축/시설관리'), ('finance', '금융/보험'), ('accounting', '회계/세무/재무'), ('logistics', '물류/운송'), ('healthcare', '의료/간호'), ('public', '공공/복지'), ('design', '디자인'), ('operation', '운영/서비스업'), ('education', '교육/강의'), ('hr', '인사/사무/총무')], max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='desired_region',
            field=models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기/인천'), ('busan', '부산/울산/경남'), ('daegu', '대구/경북'), ('gwangju', '광주/전남/전북'), ('daejeon', '대전/충남/충북'), ('gangwon', '강원'), ('jeju', '제주')], max_length=100),
        ),
    ]
