# Generated by Django 5.2.4 on 2025-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_end_year_plan_start_year_alter_plan_desired_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='career_gap_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
