# Generated by Django 5.2.4 on 2025-07-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_plan_career_gap_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='desired_job',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='desired_region',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
