# Generated by Django 5.2.4 on 2025-07-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumna', '0002_rename_comment_alumnacomment_rename_post_alumnapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnacomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alumna.alumnapost'),
        ),
    ]
